# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jerry Jong-Min Kim
email: reevid7@gmail.com
description: 김종민의 개발 블로그입니다.
github_username: Reevid
minimal_mistakes_skin: dark
search: true

repository               : "Reevid/Reevid.github.io"

logo: https://raw.githubusercontent.com/Reevid/Reevid.github.io/master/favicon.ico

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

breadcrumbs: true  # disabled by default

# search_full_content: true
google:
  search_engine_id: a881cb1a9fa9b3278

google_site_verification : "E-IZOpjA4x43YPBULfdhFQ3XQF0sHaCOHtUxo2ODDB4"
naver_site_verification: "4b02ffa47d254e19822fdb25d0655a823faf52f3"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-ESFX2F44J5"
    anonymize_ip: false # default

# teaser: /assets/images/bio-photo.jpg

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  
author:
  name   : "Jerry Jong-Min Kim"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "김종민의 개발 블로그입니다."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Reevid/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/reevidkim/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Reevid/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/reevidkim/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # # _bashshell
  # - scope:
  #     path: ""
  #     type: bashshell
  #   values:
  #     layout: single
  #     author_profile: true
  #     share: true
  #     toc: true  
  #     toc_sticky: true
  #     toc_icon: "align-left"
  #     comments: true
  # # _cycle
  # - scope:
  #     path: ""
  #     type: cycle
  #   values:
  #     layout: single
  #     author_profile: true
  #     share: true
  #     toc: true  
  #     toc_sticky: true
  #     toc_icon: "align-left"
  #     comments: true
  # _designpattern
  - scope:
      path: ""
      type: designpattern
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
  # _cleanarchitecture
  - scope:
      path: ""
      type: cleanarchitecture
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
  # _algorithm
  - scope:
      path: ""
      type: algorithm
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
  # _testing
  - scope:
      path: ""
      type: testing
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
  # _cmd
  - scope:
      path: ""
      type: cmd
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
#   bashshell:
#     Title: "Bash Shell"
#     output: true
#     permalink: /collections/:collection/:path/
  testing:
    Title: "Testing"
    output: true
    permalink: /collections/:collection/:path/
#   cycle:
#     Title: "Cycle"
#     output: true
#     permalink: /collections/:collection/:path/
  designpattern:
    Title: "Design Pattern"
    output: true
    permalink: /collections/:collection/:path/
  algorithm:
    Title: "Algorithm"
    output: true
    permalink: /collections/:collection/:path/
  cmd:
    Title: "CMD"
    output: true
    permalink: /collections/:collection/:path/
  cleanarchitecture:
    Title: "Clean Architecture"
    output: true
    permalink: /collections/:collection/:path/

comments:
  provider: "utterances"
  utterances:
    theme                : photon-dark
    issue_term           : pathname