@startuml book

skinparam componentStyle rectangle

[단위테스트]-->[빠른 피드백\n(4장)] : 극대화
[단위테스트]-->[유지 보수성\n(4장)] : 극대화
[단위테스트]-u->[도메인 모델 및 알고리즘\n(7장)] : 처리

[도메인 모델 및 알고리즘\n(7장)] -> [복잡도\n(7장)] : 높음

@enduml