@startuml book

skinparam componentStyle rectangle

[테스트 정확도\n(4장)]-->[거짓 음성\n(4장)] : 정의
[테스트 정확도\n(4장)]-r->[거짓 양성\n(4장)] : 정의

[거짓 음성\n(4장)]-->[회기 방지\n(4장)] : 해결

[거짓 양성\n(4장)]-r->[리팩터링 내성\n(4장)] : 해결

[통합 테스트]-->[회기 방지\n(4장)] : 극대화
[통합 테스트]->[리팩터링 내성\n(4장)] : 극대화
[통합 테스트]-->[컨트롤러\n(4장)] : 처리

[목\n(5장)]-u->[리팩터링 내성\n(4장)] : 잘못 사용하면 떨어짐
[목\n(5장)]-u->[통합 테스트] : 사용
[목\n(5장)]-d->[관리 의존성\n(8장)] : 사용하면 안됨
[목\n(5장)]-d->[비관리 의존성\n(8장)] : 사용해야 함

[비관리 의존성\n(8장)]-->[프로세스 외부 의존성\n(2장)] : 같음
[관리 의존성\n(8장)]-->[프로세스 외부 의존성\n(2장)] : 같음


[프로세스 외부 의존성\n(2장)]-->[협력자\n(2장)] : 같음

[컨트롤러\n(7장)]->[협력자\n(2장)] : 많음
[프로세스 내부 의존성\n(2장)]-->[협력자\n(2장)] : 같음
@enduml